# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from medusa_msgs/ImageData.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import genpy
import medusa_msgs.msg
import std_msgs.msg

class ImageData(genpy.Message):
  _md5sum = "bdeb665e166b3b92a73c5133fe56b8ec"
  _type = "medusa_msgs/ImageData"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """time timestamp	
medusa_msgs/NavStatus nav_status 
uint8 sensor_id
int32 file_dimension
std_msgs/String file_name

================================================================================
MSG: medusa_msgs/NavStatus
#NavStatus Info

medusa_msgs/Position position
medusa_msgs/AttitudeEuler attitude
medusa_msgs/VelocityNED linear_velocity
time timestamp
================================================================================
MSG: medusa_msgs/Position
#Position Info

float64 latitude
float64 longitude
float64 depth
float64 altitude
================================================================================
MSG: medusa_msgs/AttitudeEuler
float64 roll
float64 pitch
float64 yaw
================================================================================
MSG: medusa_msgs/VelocityNED
float64 north_vel
float64 east_vel
float64 down_vel
================================================================================
MSG: std_msgs/String
string data
"""
  __slots__ = ['timestamp','nav_status','sensor_id','file_dimension','file_name']
  _slot_types = ['time','medusa_msgs/NavStatus','uint8','int32','std_msgs/String']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       timestamp,nav_status,sensor_id,file_dimension,file_name

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ImageData, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.timestamp is None:
        self.timestamp = genpy.Time()
      if self.nav_status is None:
        self.nav_status = medusa_msgs.msg.NavStatus()
      if self.sensor_id is None:
        self.sensor_id = 0
      if self.file_dimension is None:
        self.file_dimension = 0
      if self.file_name is None:
        self.file_name = std_msgs.msg.String()
    else:
      self.timestamp = genpy.Time()
      self.nav_status = medusa_msgs.msg.NavStatus()
      self.sensor_id = 0
      self.file_dimension = 0
      self.file_name = std_msgs.msg.String()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2I10d2IBi().pack(_x.timestamp.secs, _x.timestamp.nsecs, _x.nav_status.position.latitude, _x.nav_status.position.longitude, _x.nav_status.position.depth, _x.nav_status.position.altitude, _x.nav_status.attitude.roll, _x.nav_status.attitude.pitch, _x.nav_status.attitude.yaw, _x.nav_status.linear_velocity.north_vel, _x.nav_status.linear_velocity.east_vel, _x.nav_status.linear_velocity.down_vel, _x.nav_status.timestamp.secs, _x.nav_status.timestamp.nsecs, _x.sensor_id, _x.file_dimension))
      _x = self.file_name.data
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.timestamp is None:
        self.timestamp = genpy.Time()
      if self.nav_status is None:
        self.nav_status = medusa_msgs.msg.NavStatus()
      if self.file_name is None:
        self.file_name = std_msgs.msg.String()
      end = 0
      _x = self
      start = end
      end += 101
      (_x.timestamp.secs, _x.timestamp.nsecs, _x.nav_status.position.latitude, _x.nav_status.position.longitude, _x.nav_status.position.depth, _x.nav_status.position.altitude, _x.nav_status.attitude.roll, _x.nav_status.attitude.pitch, _x.nav_status.attitude.yaw, _x.nav_status.linear_velocity.north_vel, _x.nav_status.linear_velocity.east_vel, _x.nav_status.linear_velocity.down_vel, _x.nav_status.timestamp.secs, _x.nav_status.timestamp.nsecs, _x.sensor_id, _x.file_dimension,) = _get_struct_2I10d2IBi().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.file_name.data = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.file_name.data = str[start:end]
      self.timestamp.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2I10d2IBi().pack(_x.timestamp.secs, _x.timestamp.nsecs, _x.nav_status.position.latitude, _x.nav_status.position.longitude, _x.nav_status.position.depth, _x.nav_status.position.altitude, _x.nav_status.attitude.roll, _x.nav_status.attitude.pitch, _x.nav_status.attitude.yaw, _x.nav_status.linear_velocity.north_vel, _x.nav_status.linear_velocity.east_vel, _x.nav_status.linear_velocity.down_vel, _x.nav_status.timestamp.secs, _x.nav_status.timestamp.nsecs, _x.sensor_id, _x.file_dimension))
      _x = self.file_name.data
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.timestamp is None:
        self.timestamp = genpy.Time()
      if self.nav_status is None:
        self.nav_status = medusa_msgs.msg.NavStatus()
      if self.file_name is None:
        self.file_name = std_msgs.msg.String()
      end = 0
      _x = self
      start = end
      end += 101
      (_x.timestamp.secs, _x.timestamp.nsecs, _x.nav_status.position.latitude, _x.nav_status.position.longitude, _x.nav_status.position.depth, _x.nav_status.position.altitude, _x.nav_status.attitude.roll, _x.nav_status.attitude.pitch, _x.nav_status.attitude.yaw, _x.nav_status.linear_velocity.north_vel, _x.nav_status.linear_velocity.east_vel, _x.nav_status.linear_velocity.down_vel, _x.nav_status.timestamp.secs, _x.nav_status.timestamp.nsecs, _x.sensor_id, _x.file_dimension,) = _get_struct_2I10d2IBi().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.file_name.data = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.file_name.data = str[start:end]
      self.timestamp.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2I10d2IBi = None
def _get_struct_2I10d2IBi():
    global _struct_2I10d2IBi
    if _struct_2I10d2IBi is None:
        _struct_2I10d2IBi = struct.Struct("<2I10d2IBi")
    return _struct_2I10d2IBi
