# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from medusa_msgs/VehicleStatus.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import genpy
import medusa_msgs.msg

class VehicleStatus(genpy.Message):
  _md5sum = "a35718b2b68a03159df7289abbd1e7c2"
  _type = "medusa_msgs/VehicleStatus"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """#VehicleStatus Info

float32 temperature
float32 humidity
float32 buoyancy
float32 internal_pressure
medusa_msgs/Battery battery
time timestamp
================================================================================
MSG: medusa_msgs/Battery
#Battery Info

medusa_msgs/NavStatus nav_status
time timestamp
float32 percentage

================================================================================
MSG: medusa_msgs/NavStatus
#NavStatus Info

medusa_msgs/Position position
medusa_msgs/AttitudeEuler attitude
medusa_msgs/VelocityNED linear_velocity
time timestamp
================================================================================
MSG: medusa_msgs/Position
#Position Info

float64 latitude
float64 longitude
float64 depth
float64 altitude
================================================================================
MSG: medusa_msgs/AttitudeEuler
float64 roll
float64 pitch
float64 yaw
================================================================================
MSG: medusa_msgs/VelocityNED
float64 north_vel
float64 east_vel
float64 down_vel"""
  __slots__ = ['temperature','humidity','buoyancy','internal_pressure','battery','timestamp']
  _slot_types = ['float32','float32','float32','float32','medusa_msgs/Battery','time']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       temperature,humidity,buoyancy,internal_pressure,battery,timestamp

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(VehicleStatus, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.temperature is None:
        self.temperature = 0.
      if self.humidity is None:
        self.humidity = 0.
      if self.buoyancy is None:
        self.buoyancy = 0.
      if self.internal_pressure is None:
        self.internal_pressure = 0.
      if self.battery is None:
        self.battery = medusa_msgs.msg.Battery()
      if self.timestamp is None:
        self.timestamp = genpy.Time()
    else:
      self.temperature = 0.
      self.humidity = 0.
      self.buoyancy = 0.
      self.internal_pressure = 0.
      self.battery = medusa_msgs.msg.Battery()
      self.timestamp = genpy.Time()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_4f10d4If2I().pack(_x.temperature, _x.humidity, _x.buoyancy, _x.internal_pressure, _x.battery.nav_status.position.latitude, _x.battery.nav_status.position.longitude, _x.battery.nav_status.position.depth, _x.battery.nav_status.position.altitude, _x.battery.nav_status.attitude.roll, _x.battery.nav_status.attitude.pitch, _x.battery.nav_status.attitude.yaw, _x.battery.nav_status.linear_velocity.north_vel, _x.battery.nav_status.linear_velocity.east_vel, _x.battery.nav_status.linear_velocity.down_vel, _x.battery.nav_status.timestamp.secs, _x.battery.nav_status.timestamp.nsecs, _x.battery.timestamp.secs, _x.battery.timestamp.nsecs, _x.battery.percentage, _x.timestamp.secs, _x.timestamp.nsecs))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.battery is None:
        self.battery = medusa_msgs.msg.Battery()
      if self.timestamp is None:
        self.timestamp = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 124
      (_x.temperature, _x.humidity, _x.buoyancy, _x.internal_pressure, _x.battery.nav_status.position.latitude, _x.battery.nav_status.position.longitude, _x.battery.nav_status.position.depth, _x.battery.nav_status.position.altitude, _x.battery.nav_status.attitude.roll, _x.battery.nav_status.attitude.pitch, _x.battery.nav_status.attitude.yaw, _x.battery.nav_status.linear_velocity.north_vel, _x.battery.nav_status.linear_velocity.east_vel, _x.battery.nav_status.linear_velocity.down_vel, _x.battery.nav_status.timestamp.secs, _x.battery.nav_status.timestamp.nsecs, _x.battery.timestamp.secs, _x.battery.timestamp.nsecs, _x.battery.percentage, _x.timestamp.secs, _x.timestamp.nsecs,) = _get_struct_4f10d4If2I().unpack(str[start:end])
      self.timestamp.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_4f10d4If2I().pack(_x.temperature, _x.humidity, _x.buoyancy, _x.internal_pressure, _x.battery.nav_status.position.latitude, _x.battery.nav_status.position.longitude, _x.battery.nav_status.position.depth, _x.battery.nav_status.position.altitude, _x.battery.nav_status.attitude.roll, _x.battery.nav_status.attitude.pitch, _x.battery.nav_status.attitude.yaw, _x.battery.nav_status.linear_velocity.north_vel, _x.battery.nav_status.linear_velocity.east_vel, _x.battery.nav_status.linear_velocity.down_vel, _x.battery.nav_status.timestamp.secs, _x.battery.nav_status.timestamp.nsecs, _x.battery.timestamp.secs, _x.battery.timestamp.nsecs, _x.battery.percentage, _x.timestamp.secs, _x.timestamp.nsecs))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.battery is None:
        self.battery = medusa_msgs.msg.Battery()
      if self.timestamp is None:
        self.timestamp = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 124
      (_x.temperature, _x.humidity, _x.buoyancy, _x.internal_pressure, _x.battery.nav_status.position.latitude, _x.battery.nav_status.position.longitude, _x.battery.nav_status.position.depth, _x.battery.nav_status.position.altitude, _x.battery.nav_status.attitude.roll, _x.battery.nav_status.attitude.pitch, _x.battery.nav_status.attitude.yaw, _x.battery.nav_status.linear_velocity.north_vel, _x.battery.nav_status.linear_velocity.east_vel, _x.battery.nav_status.linear_velocity.down_vel, _x.battery.nav_status.timestamp.secs, _x.battery.nav_status.timestamp.nsecs, _x.battery.timestamp.secs, _x.battery.timestamp.nsecs, _x.battery.percentage, _x.timestamp.secs, _x.timestamp.nsecs,) = _get_struct_4f10d4If2I().unpack(str[start:end])
      self.timestamp.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_4f10d4If2I = None
def _get_struct_4f10d4If2I():
    global _struct_4f10d4If2I
    if _struct_4f10d4If2I is None:
        _struct_4f10d4If2I = struct.Struct("<4f10d4If2I")
    return _struct_4f10d4If2I
