# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from medusa_msgs/Velocity.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import genpy
import medusa_msgs.msg

class Velocity(genpy.Message):
  _md5sum = "89c3e51eae0c79f238e531a3238e0f88"
  _type = "medusa_msgs/Velocity"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """#Velocity Info

medusa_msgs/VelocityNED ned_velocity
medusa_msgs/VelocityBody body_velocity
float64 speed #module of the velocity vector
time timestamp
================================================================================
MSG: medusa_msgs/VelocityNED
float64 north_vel
float64 east_vel
float64 down_vel
================================================================================
MSG: medusa_msgs/VelocityBody
float64 vx
float64 vy
float64 vz"""
  __slots__ = ['ned_velocity','body_velocity','speed','timestamp']
  _slot_types = ['medusa_msgs/VelocityNED','medusa_msgs/VelocityBody','float64','time']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       ned_velocity,body_velocity,speed,timestamp

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Velocity, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.ned_velocity is None:
        self.ned_velocity = medusa_msgs.msg.VelocityNED()
      if self.body_velocity is None:
        self.body_velocity = medusa_msgs.msg.VelocityBody()
      if self.speed is None:
        self.speed = 0.
      if self.timestamp is None:
        self.timestamp = genpy.Time()
    else:
      self.ned_velocity = medusa_msgs.msg.VelocityNED()
      self.body_velocity = medusa_msgs.msg.VelocityBody()
      self.speed = 0.
      self.timestamp = genpy.Time()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_7d2I().pack(_x.ned_velocity.north_vel, _x.ned_velocity.east_vel, _x.ned_velocity.down_vel, _x.body_velocity.vx, _x.body_velocity.vy, _x.body_velocity.vz, _x.speed, _x.timestamp.secs, _x.timestamp.nsecs))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.ned_velocity is None:
        self.ned_velocity = medusa_msgs.msg.VelocityNED()
      if self.body_velocity is None:
        self.body_velocity = medusa_msgs.msg.VelocityBody()
      if self.timestamp is None:
        self.timestamp = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 64
      (_x.ned_velocity.north_vel, _x.ned_velocity.east_vel, _x.ned_velocity.down_vel, _x.body_velocity.vx, _x.body_velocity.vy, _x.body_velocity.vz, _x.speed, _x.timestamp.secs, _x.timestamp.nsecs,) = _get_struct_7d2I().unpack(str[start:end])
      self.timestamp.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_7d2I().pack(_x.ned_velocity.north_vel, _x.ned_velocity.east_vel, _x.ned_velocity.down_vel, _x.body_velocity.vx, _x.body_velocity.vy, _x.body_velocity.vz, _x.speed, _x.timestamp.secs, _x.timestamp.nsecs))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.ned_velocity is None:
        self.ned_velocity = medusa_msgs.msg.VelocityNED()
      if self.body_velocity is None:
        self.body_velocity = medusa_msgs.msg.VelocityBody()
      if self.timestamp is None:
        self.timestamp = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 64
      (_x.ned_velocity.north_vel, _x.ned_velocity.east_vel, _x.ned_velocity.down_vel, _x.body_velocity.vx, _x.body_velocity.vy, _x.body_velocity.vz, _x.speed, _x.timestamp.secs, _x.timestamp.nsecs,) = _get_struct_7d2I().unpack(str[start:end])
      self.timestamp.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_7d2I = None
def _get_struct_7d2I():
    global _struct_7d2I
    if _struct_7d2I is None:
        _struct_7d2I = struct.Struct("<7d2I")
    return _struct_7d2I
