// Generated by gencpp from file medusa_msgs/CameraGet.msg
// DO NOT EDIT!


#ifndef MEDUSA_MSGS_MESSAGE_CAMERAGET_H
#define MEDUSA_MSGS_MESSAGE_CAMERAGET_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/String.h>

namespace medusa_msgs
{
template <class ContainerAllocator>
struct CameraGet_
{
  typedef CameraGet_<ContainerAllocator> Type;

  CameraGet_()
    : id_camera(0)
    , filename()  {
    }
  CameraGet_(const ContainerAllocator& _alloc)
    : id_camera(0)
    , filename(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _id_camera_type;
  _id_camera_type id_camera;

   typedef  ::std_msgs::String_<ContainerAllocator>  _filename_type;
  _filename_type filename;





  typedef boost::shared_ptr< ::medusa_msgs::CameraGet_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::medusa_msgs::CameraGet_<ContainerAllocator> const> ConstPtr;

}; // struct CameraGet_

typedef ::medusa_msgs::CameraGet_<std::allocator<void> > CameraGet;

typedef boost::shared_ptr< ::medusa_msgs::CameraGet > CameraGetPtr;
typedef boost::shared_ptr< ::medusa_msgs::CameraGet const> CameraGetConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::medusa_msgs::CameraGet_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::medusa_msgs::CameraGet_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::medusa_msgs::CameraGet_<ContainerAllocator1> & lhs, const ::medusa_msgs::CameraGet_<ContainerAllocator2> & rhs)
{
  return lhs.id_camera == rhs.id_camera &&
    lhs.filename == rhs.filename;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::medusa_msgs::CameraGet_<ContainerAllocator1> & lhs, const ::medusa_msgs::CameraGet_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace medusa_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::medusa_msgs::CameraGet_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::medusa_msgs::CameraGet_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::medusa_msgs::CameraGet_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::medusa_msgs::CameraGet_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::medusa_msgs::CameraGet_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::medusa_msgs::CameraGet_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::medusa_msgs::CameraGet_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2f97773bf93ac3afe9db99951b0af3fe";
  }

  static const char* value(const ::medusa_msgs::CameraGet_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2f97773bf93ac3afULL;
  static const uint64_t static_value2 = 0xe9db99951b0af3feULL;
};

template<class ContainerAllocator>
struct DataType< ::medusa_msgs::CameraGet_<ContainerAllocator> >
{
  static const char* value()
  {
    return "medusa_msgs/CameraGet";
  }

  static const char* value(const ::medusa_msgs::CameraGet_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::medusa_msgs::CameraGet_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"uint8 id_camera\n"
"\n"
"std_msgs/String filename\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/String\n"
"string data\n"
;
  }

  static const char* value(const ::medusa_msgs::CameraGet_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::medusa_msgs::CameraGet_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id_camera);
      stream.next(m.filename);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CameraGet_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::medusa_msgs::CameraGet_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::medusa_msgs::CameraGet_<ContainerAllocator>& v)
  {
    s << indent << "id_camera: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.id_camera);
    s << indent << "filename: ";
    s << std::endl;
    Printer< ::std_msgs::String_<ContainerAllocator> >::stream(s, indent + "  ", v.filename);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MEDUSA_MSGS_MESSAGE_CAMERAGET_H
