// Generated by gencpp from file medusa_msgs/Command.msg
// DO NOT EDIT!


#ifndef MEDUSA_MSGS_MESSAGE_COMMAND_H
#define MEDUSA_MSGS_MESSAGE_COMMAND_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/String.h>

namespace medusa_msgs
{
template <class ContainerAllocator>
struct Command_
{
  typedef Command_<ContainerAllocator> Type;

  Command_()
    : command()  {
    }
  Command_(const ContainerAllocator& _alloc)
    : command(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::String_<ContainerAllocator>  _command_type;
  _command_type command;





  typedef boost::shared_ptr< ::medusa_msgs::Command_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::medusa_msgs::Command_<ContainerAllocator> const> ConstPtr;

}; // struct Command_

typedef ::medusa_msgs::Command_<std::allocator<void> > Command;

typedef boost::shared_ptr< ::medusa_msgs::Command > CommandPtr;
typedef boost::shared_ptr< ::medusa_msgs::Command const> CommandConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::medusa_msgs::Command_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::medusa_msgs::Command_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::medusa_msgs::Command_<ContainerAllocator1> & lhs, const ::medusa_msgs::Command_<ContainerAllocator2> & rhs)
{
  return lhs.command == rhs.command;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::medusa_msgs::Command_<ContainerAllocator1> & lhs, const ::medusa_msgs::Command_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace medusa_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::medusa_msgs::Command_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::medusa_msgs::Command_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::medusa_msgs::Command_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::medusa_msgs::Command_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::medusa_msgs::Command_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::medusa_msgs::Command_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::medusa_msgs::Command_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b45d65857bb7a4d869afeb1d0e4bf0c7";
  }

  static const char* value(const ::medusa_msgs::Command_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb45d65857bb7a4d8ULL;
  static const uint64_t static_value2 = 0x69afeb1d0e4bf0c7ULL;
};

template<class ContainerAllocator>
struct DataType< ::medusa_msgs::Command_<ContainerAllocator> >
{
  static const char* value()
  {
    return "medusa_msgs/Command";
  }

  static const char* value(const ::medusa_msgs::Command_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::medusa_msgs::Command_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/String command\n"
"================================================================================\n"
"MSG: std_msgs/String\n"
"string data\n"
;
  }

  static const char* value(const ::medusa_msgs::Command_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::medusa_msgs::Command_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.command);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Command_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::medusa_msgs::Command_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::medusa_msgs::Command_<ContainerAllocator>& v)
  {
    s << indent << "command: ";
    s << std::endl;
    Printer< ::std_msgs::String_<ContainerAllocator> >::stream(s, indent + "  ", v.command);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MEDUSA_MSGS_MESSAGE_COMMAND_H
