// Generated by gencpp from file medusa_msgs/SensorMeasurement.msg
// DO NOT EDIT!


#ifndef MEDUSA_MSGS_MESSAGE_SENSORMEASUREMENT_H
#define MEDUSA_MSGS_MESSAGE_SENSORMEASUREMENT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <medusa_msgs/NavStatus.h>

namespace medusa_msgs
{
template <class ContainerAllocator>
struct SensorMeasurement_
{
  typedef SensorMeasurement_<ContainerAllocator> Type;

  SensorMeasurement_()
    : timestamp()
    , nav_status()
    , measurement_name()
    , sensor_id(0)
    , sample(0.0)
    , frequency(0.0)
    , error(0)  {
    }
  SensorMeasurement_(const ContainerAllocator& _alloc)
    : timestamp()
    , nav_status(_alloc)
    , measurement_name(_alloc)
    , sensor_id(0)
    , sample(0.0)
    , frequency(0.0)
    , error(0)  {
  (void)_alloc;
    }



   typedef ros::Time _timestamp_type;
  _timestamp_type timestamp;

   typedef  ::medusa_msgs::NavStatus_<ContainerAllocator>  _nav_status_type;
  _nav_status_type nav_status;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _measurement_name_type;
  _measurement_name_type measurement_name;

   typedef uint8_t _sensor_id_type;
  _sensor_id_type sensor_id;

   typedef float _sample_type;
  _sample_type sample;

   typedef float _frequency_type;
  _frequency_type frequency;

   typedef int16_t _error_type;
  _error_type error;





  typedef boost::shared_ptr< ::medusa_msgs::SensorMeasurement_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::medusa_msgs::SensorMeasurement_<ContainerAllocator> const> ConstPtr;

}; // struct SensorMeasurement_

typedef ::medusa_msgs::SensorMeasurement_<std::allocator<void> > SensorMeasurement;

typedef boost::shared_ptr< ::medusa_msgs::SensorMeasurement > SensorMeasurementPtr;
typedef boost::shared_ptr< ::medusa_msgs::SensorMeasurement const> SensorMeasurementConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::medusa_msgs::SensorMeasurement_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::medusa_msgs::SensorMeasurement_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::medusa_msgs::SensorMeasurement_<ContainerAllocator1> & lhs, const ::medusa_msgs::SensorMeasurement_<ContainerAllocator2> & rhs)
{
  return lhs.timestamp == rhs.timestamp &&
    lhs.nav_status == rhs.nav_status &&
    lhs.measurement_name == rhs.measurement_name &&
    lhs.sensor_id == rhs.sensor_id &&
    lhs.sample == rhs.sample &&
    lhs.frequency == rhs.frequency &&
    lhs.error == rhs.error;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::medusa_msgs::SensorMeasurement_<ContainerAllocator1> & lhs, const ::medusa_msgs::SensorMeasurement_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace medusa_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::medusa_msgs::SensorMeasurement_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::medusa_msgs::SensorMeasurement_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::medusa_msgs::SensorMeasurement_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::medusa_msgs::SensorMeasurement_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::medusa_msgs::SensorMeasurement_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::medusa_msgs::SensorMeasurement_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::medusa_msgs::SensorMeasurement_<ContainerAllocator> >
{
  static const char* value()
  {
    return "30226808724a611420a1dfa82ca2c2ea";
  }

  static const char* value(const ::medusa_msgs::SensorMeasurement_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x30226808724a6114ULL;
  static const uint64_t static_value2 = 0x20a1dfa82ca2c2eaULL;
};

template<class ContainerAllocator>
struct DataType< ::medusa_msgs::SensorMeasurement_<ContainerAllocator> >
{
  static const char* value()
  {
    return "medusa_msgs/SensorMeasurement";
  }

  static const char* value(const ::medusa_msgs::SensorMeasurement_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::medusa_msgs::SensorMeasurement_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#Measurement obtained by a sensor\n"
"\n"
"time timestamp	\n"
"medusa_msgs/NavStatus nav_status \n"
"string measurement_name\n"
"uint8 sensor_id\n"
"float32 sample	#Sensor measurement value\n"
"float32 frequency\n"
"int16 error\n"
"\n"
"================================================================================\n"
"MSG: medusa_msgs/NavStatus\n"
"#NavStatus Info\n"
"\n"
"medusa_msgs/Position position\n"
"medusa_msgs/AttitudeEuler attitude\n"
"medusa_msgs/VelocityNED linear_velocity\n"
"time timestamp\n"
"================================================================================\n"
"MSG: medusa_msgs/Position\n"
"#Position Info\n"
"\n"
"float64 latitude\n"
"float64 longitude\n"
"float64 depth\n"
"float64 altitude\n"
"================================================================================\n"
"MSG: medusa_msgs/AttitudeEuler\n"
"float64 roll\n"
"float64 pitch\n"
"float64 yaw\n"
"================================================================================\n"
"MSG: medusa_msgs/VelocityNED\n"
"float64 north_vel\n"
"float64 east_vel\n"
"float64 down_vel\n"
;
  }

  static const char* value(const ::medusa_msgs::SensorMeasurement_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::medusa_msgs::SensorMeasurement_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.timestamp);
      stream.next(m.nav_status);
      stream.next(m.measurement_name);
      stream.next(m.sensor_id);
      stream.next(m.sample);
      stream.next(m.frequency);
      stream.next(m.error);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SensorMeasurement_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::medusa_msgs::SensorMeasurement_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::medusa_msgs::SensorMeasurement_<ContainerAllocator>& v)
  {
    s << indent << "timestamp: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.timestamp);
    s << indent << "nav_status: ";
    s << std::endl;
    Printer< ::medusa_msgs::NavStatus_<ContainerAllocator> >::stream(s, indent + "  ", v.nav_status);
    s << indent << "measurement_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.measurement_name);
    s << indent << "sensor_id: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.sensor_id);
    s << indent << "sample: ";
    Printer<float>::stream(s, indent + "  ", v.sample);
    s << indent << "frequency: ";
    Printer<float>::stream(s, indent + "  ", v.frequency);
    s << indent << "error: ";
    Printer<int16_t>::stream(s, indent + "  ", v.error);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MEDUSA_MSGS_MESSAGE_SENSORMEASUREMENT_H
