(cl:in-package medusa_msgs-msg)
(cl:export '(MANEUVER_NAME-VAL
          MANEUVER_NAME
          POSITION-VAL
          POSITION
          Z_UNITS-VAL
          Z_UNITS
          SPEED_UNITS-VAL
          SPEED_UNITS
          SPEED-VAL
          SPEED
          TIMEOUT-VAL
          TIMEOUT
          RADIUS-VAL
          RADIUS
          DURATION-VAL
          DURATION
          DOCKING_ID-VAL
          DOCKING_ID
          DOCKING_MANEUVER-VAL
          DOCKING_MANEUVER
          WAYPOINT_1-VAL
          WAYPOINT_1
          WAYPOINT_2-VAL
          WAYPOINT_2
          WAYPOINT_3-VAL
          WAYPOINT_3
          TRACK_SPACING-VAL
          TRACK_SPACING
          ACROSS_TRACKS-VAL
          ACROSS_TRACKS
))